project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /src/usr/local/emhttp/plugins/tailscale/locales/en_US.json
    translation: /src/usr/local/emhttp/plugins/tailscale/locales/%locale_with_underscore%.json
