on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir release
          cd src
          tar --owner=0 --group=0 -cJf ../release/unraid-tailscale-utils-${{ github.event.release.name}}-noarch-1.txz *
          cd ../release
          sha256sum unraid-tailscale-utils-${{ github.event.release.name}}-noarch-1.txz | awk '{print $1}' > unraid-tailscale-utils-${{ github.event.release.name}}-noarch-1.txz.sha256

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/*
  